### ISSUE TITLE
Getting error when I run pact verification

### ISSUE THREAD

**Issue by mlinder69** [DiUS/pact-workshop-js#13]
Hi,
unfortunately I have an error when I run npm run "test:pact:provider":

> pact-workshop-js@1.0.0 test:pact:provider C:\Users\tgdlima3\workspace0056\pact\pact-workshop-js-v1
> mocha --timeout 10000 provider/test/providerPact.spec.js

Provider service listening on http://localhost:8081
  Pact Verification
[2020-02-26T10:09:41.229Z]  INFO: pact-node@6.20.0/5376 on U318882: Verifying Pacts.
[2020-02-26T10:09:41.232Z]  INFO: pact-node@6.20.0/5376 on U318882: Verifying Pact Files
[2020-02-26T10:09:41.248Z]  INFO: pact-node@6.20.0/5376 on U318882: Created 'standalone\win32-1.61.1\bin\pact-provider-verifier.bat '/Users/tgdlima3/workspace0056/pact/pact-workshop-js-v1/pacts/our_little_consumer-our_provider.json'
 --provider-base-url 'http://localhost:8081'' process with PID: 15640
[2020-02-26T10:09:41.973Z]  WARN: pact-node@6.20.0/5376 on U318882: Pact exited with code 1.
    1) should validate the expectations of Our Little Consumer

  0 passing (751ms)
  1 failing

  1) Pact Verification should validate the expectations of Our Little Consumer:
     Error: C:/Users/tgdlima3/workspace0056/pact/pact-workshop-js-v1/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/app.rb:3:in `re
quire': cannot load such file -- pact/provider_verifier/provider_states/remove_provider_states_header_middleware (LoadError)
        from C:/Users/tgdlima3/workspace0056/pact/pact-workshop-js-v1/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/app.rb:3:in `<
top (required)>'
        from C:/Users/tgdlima3/workspace0056/pact/pact-workshop-js-v1/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/cli/verify.rb:
3:in `require'
        from C:/Users/tgdlima3/workspace0056/pact/pact-workshop-js-v1/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.20.0/lib/pact/provider_verifier/cli/verify.rb:
3:in `<top (required)>'
        from C:/Users/tgdlima3/workspace0056/pact/pact-workshop-js-v1/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/app/pact-provider-verifier.rb:18:in `require'

        from C:/Users/tgdlima3/workspace0056/pact/pact-workshop-js-v1/node_modules/@pact-foundation/pact-node/standalone/win32-1.61.1/lib/app/pact-provider-verifier.rb:18:in `<main>'

      at ChildProcess.<anonymous> (node_modules\@pact-foundation\pact-node\src\verifier.js:130:68)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pact-workshop-js@1.0.0 test:pact:provider: `mocha --timeout 10000 provider/test/providerPact.spec.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pact-workshop-js@1.0.0 test:pact:provider script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tgdlima3\AppData\Roaming\npm-cache\_logs\2020-02-26T10_09_42_009Z-debug.log

Any idea what is wrong here?
Thanks for support. 

Best Regards,
Marco

**Comment by mefellows** [comment]
I think you're hitting the file path length issues in Windows. Try moving the test to a folder closer to c: (Google the issue)

Also, there is a newer workshop listed on the readme you should move to

**Comment by mlinder69** [comment]
Exactly this was the case! Thanks so mutch for help. Br Marco
