### ISSUE TITLE
regex test for validDate should not assume '+' in the timeZone

### ISSUE THREAD

**Issue by jiixing** [DiUS/pact-workshop-js#3]
I am testing in North America and the timeZone is  -  instead of +  

                  validDate: term({ generate: date, matcher: '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}-\\d{2}:\\d{2}' }),

       "body": {
          "test": "NO",
          "validDate": "2013-08-16T15:31:20-10:00",
          "count": 1000
        },

**Comment by mefellows** [comment]
Thanks @jiixing, I have fixed this in the latest workshop (I'm about to run a workshop in North America and noticed it too(.

Apologies for the delay, I've setup alerts on this repo now.
