### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by BrendonFlanagan** [DiUS/pact-workshop-js#8]
Upon checking out the latest, there are still some minor typos, but I can only get as far as Step 3 and simply cannot get the pact to validate.

Can you please re-test this yourself and provide an updated starting point and step by step guide.  Please, please, please.

**Comment by mefellows** [comment]
Clean checkout of step 3, ensuring no artefacts remain from previous steps:

![screenshot](https://user-images.githubusercontent.com/53900/53405644-60d37480-3a0c-11e9-9644-70c2d07eb363.png)

If there are minor typos, we'd love feedback/PR to fix them!

Are you able to please show what's not working and we can go from there? I ran this workshop in November and we didn't have any issues on this step.

Also, any OS and other relevant detail would be helpful.

**Comment by BrendonFlanagan** [comment]
Possibly best to start from the beginning as maybe thats where it begins to go wrong.

Downloaded the zipped version.

At step 1

Running 

$ node provider/provider.js

Does nothing, but $ node provider/providerService.js works

Provider Service listening on http://localhost:9123

Then

$ node consumer/consumer.js
{ test: 'NO', validDate: '2017-06-12T06:25:42.392Z', count: 100 }

Doesn't produce the above, it instead produces

{ count: 0.1, date: '2019-02-27T20:37:18+13:00' }


I've attached the zip file so you can confirm.


Thanks

Brendon.

**Comment by mefellows** [comment]
> Downloaded the zipped version.

You can't do this. You need to use git, as each step is tied to a branch in the git repository.

I realise this may not be obvious to others, and so will add a note to the top of the readme now..

**Comment by mefellows** [comment]
I've just made a small update to the readme. Hopefully this gets you moving, apologies for any confusion.

**Comment by BrendonFlanagan** [comment]
Cool, thanks for that, I only had time to do step 1 tonight, worked as expected, so I should be all good now.

Brendon.

**Comment by mefellows** [comment]
No dramas. If you haven't already, worth jumping into slack.pact.io and joining the community :)
